### ISSUE TITLE
poeblix does not properly handle dependencies that include uppercase letters

### ISSUE THREAD

**Issue by filips123** [spoorn/poeblix#11]
Some Python packages, for example, `SQLAlchemy`, `PyMuPDF`, `Flask` and others, have a name that includes some uppercase letters. This is normally not a problem, because `pip` and `poetry` both correctly handle such dependencies regardless of whether you use the all-lowercase name or the "official" mixedcase name, and treat both names as one dependency.

However, this is not the case for `poeblix`. Considering a simple Poetry package that has the following `pyproject.toml`:

```toml
[tool.poetry]
name = "example-package"
version = "0.0.0"
description = "An example package demonstrating poeblix issue"
authors = ["John Smith <john@example.com>"]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.2"
SQLAlchemy = "^2.0.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

Poetry correctly installs both dependencies, with all dependencies, including `SQLAlchemy`, being written in lowercase in `poetry.lock`. When generating a wheel with default `poetry build`, it correctly specifies both dependencies in their original casing:

```
Requires-Dist: SQLAlchemy (>=2.0.9,<3.0.0)
Requires-Dist: requests (>=2.28.2,<3.0.0)
```

When generating a wheel with `poetry blixbuild`, however, the `requests` dependency (which has been written in lowercase) is correctly processed, while the `SQLAlchemy` dependency is duplicated, once with loose requirements and original casing from `pyproject.toml`, and once with strict version and in lowercase from `poetry.lock`:

```
Requires-Dist: SQLAlchemy (>=2.0.9,<3.0.0)
Requires-Dist: certifi (==2022.12.7)
Requires-Dist: charset-normalizer (==3.1.0)
Requires-Dist: greenlet (==2.0.2)
Requires-Dist: idna (==3.4)
Requires-Dist: requests (>=2.28.2,<3.0.0)
Requires-Dist: sqlalchemy (==2.0.9)
Requires-Dist: typing-extensions (==4.5.0)
Requires-Dist: urllib3 (==1.26.15)
```

Additionally, when generating a wheel with `poetry blixbuild --only-lock`, only the lowercase version from `poetry.lock` is included (which is expected), however, this causes the validation to fail:

```
Requires-Dist: certifi (==2022.12.7)
Requires-Dist: charset-normalizer (==3.1.0)
Requires-Dist: greenlet (==2.0.2)
Requires-Dist: idna (==3.4)
Requires-Dist: requests (==2.28.2)
Requires-Dist: sqlalchemy (==2.0.9)
Requires-Dist: typing-extensions (==4.5.0)
Requires-Dist: urllib3 (==1.26.15)
```

```
$ poetry blixvalidatewheel dist/example_package-0.0.0-py3-none-any.whl
Validating Requires Dist for wheel [dist/example_package-0.0.0-py3-none-any.whl] against pyproject.toml/poetry.lock
Validating against pyproject.toml...
Packages in pyproject.toml are not present in the Wheel file: ['SQLAlchemy']
```

I think the solution for this would be to make `poeblix` treat all case variations of the dependency name as one dependency. This could be probably done by "normalizing" all of them to an all-lowercase name.
