### ISSUE TITLE
Non-normalized package names in `pyproject.toml` result in duplicate dependencies in METADATA

### ISSUE THREAD

**Issue by edgarrmondragon** [spoorn/poeblix#20]
When using `poetry blixbuild`, the following dependencies:

```toml
[tool.poetry.dependencies]
python = "^3.11"
"ruamel.yaml" = "^0.17.21"
```

result in

```
Requires-Dist: ruamel-yaml (==0.17.40)
Requires-Dist: ruamel-yaml-clib (==0.2.8)
Requires-Dist: ruamel.yaml (>=0.17.21,<0.18.0)
```

while

```toml
[tool.poetry.dependencies]
python = "^3.11"
"ruamel-yaml" = "^0.17.21"
```

results in

```
Requires-Dist: ruamel-yaml (>=0.17.21,<0.18.0)
Requires-Dist: ruamel-yaml-clib (==0.2.8)
```
